server:
  port: 9091

spring:
  thymeleaf:
    cache: false
    mode: html

weixin:
  mp:
    property:
      appid:
      app-secret:
      mchid:
  pay:
    v2:
      appid:
      mchid:
      key:
      cert-path:
      notify-url:
      refund-notify-url:
    v3:
      appid:
      mchid:
      serial-no:
      key:
      cert-path:
      notify-url:
      refund-notify-url:
logging:
  level:
    top.codewood.wx: debug